export type Locale = "en" | "sv";

export const uiCopy = {
  en: {
    languageName: "English",
    languageSwitchLabel: "Change language",
    nav: {
      home: "Car Finder home",
      findCars: "Find a car",
      howItWorks: "How it works",
      saved: "Saved",
      savedCars: (count: number) => `${count} saved cars`,
    },
    hero: {
      eyebrow: "Smarter car buying starts here",
      title: "Find the car worth buying.",
      description:
        "We compare market value, ownership cost and reliability so you can find the best buys—not just more listings.",
      searchLabel: "Search by make or model",
      searchPlaceholder: "Try “Volvo V60” or “Tesla Model 3”",
      showCars: (count: number) => `Show ${count} ${count === 1 ? "car" : "cars"}`,
      popular: "Popular",
      suggestionsLabel: "Popular searches",
      benefits: [
        "Market value analyzed",
        "Ownership cost estimated",
        "Reliability considered",
      ],
    },
    filters: {
      title: "Filters",
      reset: "Reset",
      resetAll: "Reset all",
      budget: "Price range",
      anyBudget: "Any budget",
      minimum: "From",
      maximum: "To",
      noMinimum: "0 SEK",
      noMaximum: "Any price",
      minimumBudget: "Minimum price",
      maximumBudget: "Maximum price",
      make: "Make",
      allMakes: "All makes",
      searchMakes: "Search makes",
      model: "Model",
      allModels: "All models",
      searchModels: "Search models",
      noMatches: "No matching options",
      fuel: "Fuel",
      any: "Any",
      transmission: "Transmission",
      year: "Year from",
      anyYear: "Any year",
      mileage: "Max mileage",
      anyMileage: "Any mileage",
      body: "Body style",
      fuels: {
        electric: "Electric",
        plug_in_hybrid: "Plug-in",
        self_charging_hybrid: "Hybrid",
        petrol: "Petrol",
        diesel: "Diesel",
        ethanol: "Ethanol",
        hydrogen: "Hydrogen",
        other: "Other",
      },
      transmissions: { automatic: "Automatic", manual: "Manual", other: "Other" },
      bodies: {
        convertible: "Convertible",
        coupe: "Coupé",
        estate: "Estate",
        hatchback: "Hatchback",
        minivan: "Minivan",
        pickup: "Pickup",
        sedan: "Sedan",
        suv: "SUV",
        van: "Van",
        other: "Other",
      },
    },
    results: {
      eyebrow: "Analyzed for you",
      title: "Best buys right now",
      matchCount: (shown: number, total: number) =>
        `${shown} of ${total} analyzed ${total === 1 ? "car" : "cars"} match`,
      rangeCount: (first: number, last: number, total: number) =>
        `Showing ${first}–${last} of ${total.toLocaleString("en-SE")} cars`,
      pageMatchCount: (shown: number, total: number) =>
        `${shown} match on this page · ${total.toLocaleString("en-SE")} cars total`,
      synchronized: "Synced",
      filterButton: "Filters",
      sortLabel: "Sort",
      sortAria: "Sort results",
      sorts: {
        deal_score: "Best Deal Score",
        buy_confidence: "Highest confidence",
        price_asc: "Lowest price",
        price_desc: "Highest price",
        newest: "Newest model year",
      },
      activeFilters: "Active filters",
      removeFilter: (label: string) => `Remove filter: ${label}`,
      noResultsTitle: "No cars match yet",
      noResultsBody:
        "Try another make, increase your budget or reset the filters to see every analyzed car.",
      clearFilters: "Clear filters",
      mobileTitle: "Refine your search",
      closeFilters: "Close filters",
      paginationLabel: "Vehicle result pages",
      pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
      previousPage: "Previous",
      nextPage: "Next page",
      pageNumbers: "Choose a result page",
      goToPage: (page: number) => `Go to page ${page}`,
    },
    card: {
      dealScore: "Deal Score",
      confidence: "Buy confidence",
      exceptional: "Exceptional",
      veryGood: "Very good",
      average: "Average",
      poor: "Poor",
      missingImage: "Image unavailable",
      removeSaved: "Remove from saved",
      saveCar: "Save car",
      reduced: "Reduced",
      mileageUnit: "km",
      marketValue: "Market value",
      save: "Save",
      belowMarket: (percent: number) => `${percent}% below market`,
      aboveMarket: (percent: number) => `${percent}% above market`,
      atMarket: "At estimated market value",
      dealScoreHelp: "Price attractiveness compared with similar cars.",
      confidenceHelp: "Overall purchase quality, ownership cost and risk.",
      financingFrom: "Financing from",
      perMonth: "/mo",
      viewListing: "View listing",
      scoreOutOf: (label: string, value: number) => `${label}: ${value} out of 100`,
    },
    filterLabels: {
      max: "Max",
      from: "From",
    },
    footer: {
      tagline: "A more confident way to choose a car.",
      disclaimer: "Market values and costs are estimates, not guarantees.",
    },
  },
  sv: {
    languageName: "Svenska",
    languageSwitchLabel: "Byt språk",
    nav: {
      home: "Car Finder hem",
      findCars: "Hitta bil",
      howItWorks: "Så fungerar det",
      saved: "Sparade",
      savedCars: (count: number) => `${count} sparade bilar`,
    },
    hero: {
      eyebrow: "Smartare bilköp börjar här",
      title: "Hitta bilen som är värd att köpa.",
      description:
        "Vi jämför marknadsvärde, ägandekostnad och tillförlitlighet så att du hittar de bästa köpen — inte bara fler annonser.",
      searchLabel: "Sök efter märke eller modell",
      searchPlaceholder: "Prova ”Volvo V60” eller ”Tesla Model 3”",
      showCars: (count: number) => `Visa ${count} ${count === 1 ? "bil" : "bilar"}`,
      popular: "Populärt",
      suggestionsLabel: "Populära sökningar",
      benefits: [
        "Marknadsvärde analyserat",
        "Ägandekostnad uppskattad",
        "Tillförlitlighet bedömd",
      ],
    },
    filters: {
      title: "Filter",
      reset: "Återställ",
      resetAll: "Rensa alla",
      budget: "Prisintervall",
      anyBudget: "Alla priser",
      minimum: "Från",
      maximum: "Till",
      noMinimum: "0 kr",
      noMaximum: "Alla priser",
      minimumBudget: "Lägsta pris",
      maximumBudget: "Högsta pris",
      make: "Märke",
      allMakes: "Alla märken",
      searchMakes: "Sök bilmärke",
      model: "Modell",
      allModels: "Alla modeller",
      searchModels: "Sök modell",
      noMatches: "Inga matchande alternativ",
      fuel: "Drivmedel",
      any: "Alla",
      transmission: "Växellåda",
      year: "Från årsmodell",
      anyYear: "Alla år",
      mileage: "Max miltal",
      anyMileage: "Alla miltal",
      body: "Karosstyp",
      fuels: {
        electric: "El",
        plug_in_hybrid: "Laddhybrid",
        self_charging_hybrid: "Hybrid",
        petrol: "Bensin",
        diesel: "Diesel",
        ethanol: "Etanol",
        hydrogen: "Vätgas",
        other: "Övrigt",
      },
      transmissions: { automatic: "Automat", manual: "Manuell", other: "Övrig" },
      bodies: {
        convertible: "Cabriolet",
        coupe: "Coupé",
        estate: "Kombi",
        hatchback: "Halvkombi",
        minivan: "Minibuss",
        pickup: "Pickup",
        sedan: "Sedan",
        suv: "SUV",
        van: "Skåpbil",
        other: "Övrig",
      },
    },
    results: {
      eyebrow: "Analyserat för dig",
      title: "Bästa köpen just nu",
      matchCount: (shown: number, total: number) =>
        `${shown} av ${total} analyserade ${total === 1 ? "bil" : "bilar"} matchar`,
      rangeCount: (first: number, last: number, total: number) =>
        `Visar ${first}–${last} av ${total.toLocaleString("sv-SE")} bilar`,
      pageMatchCount: (shown: number, total: number) =>
        `${shown} matchar på sidan · ${total.toLocaleString("sv-SE")} bilar totalt`,
      synchronized: "Synkad",
      filterButton: "Filter",
      sortLabel: "Sortera",
      sortAria: "Sortera resultat",
      sorts: {
        deal_score: "Bäst Deal Score",
        buy_confidence: "Högst köptrygghet",
        price_asc: "Lägst pris",
        price_desc: "Högst pris",
        newest: "Nyast årsmodell",
      },
      activeFilters: "Aktiva filter",
      removeFilter: (label: string) => `Ta bort filter: ${label}`,
      noResultsTitle: "Inga bilar matchar ännu",
      noResultsBody:
        "Prova ett annat märke, höj maxpriset eller rensa filtren för att se alla analyserade bilar.",
      clearFilters: "Rensa filter",
      mobileTitle: "Anpassa din sökning",
      closeFilters: "Stäng filter",
      paginationLabel: "Resultatsidor för bilar",
      pageOf: (page: number, total: number) => `Sida ${page} av ${total}`,
      previousPage: "Föregående",
      nextPage: "Nästa sida",
      pageNumbers: "Välj en resultatsida",
      goToPage: (page: number) => `Gå till sida ${page}`,
    },
    card: {
      dealScore: "Deal Score",
      confidence: "Köptrygghet",
      exceptional: "Exceptionellt",
      veryGood: "Mycket bra",
      average: "Genomsnittligt",
      poor: "Svagt",
      missingImage: "Bild saknas",
      removeSaved: "Ta bort från sparade",
      saveCar: "Spara bilen",
      reduced: "Sänkt",
      mileageUnit: "mil",
      marketValue: "Marknadsvärde",
      save: "Spara",
      belowMarket: (percent: number) => `${percent}% under marknaden`,
      aboveMarket: (percent: number) => `${percent}% över marknaden`,
      atMarket: "Vid uppskattat marknadsvärde",
      dealScoreHelp: "Prisets attraktivitet jämfört med liknande bilar.",
      confidenceHelp: "Helhetsbedömning av kvalitet, ägandekostnad och risk.",
      financingFrom: "Finansiering från",
      perMonth: "/mån",
      viewListing: "Visa annons",
      scoreOutOf: (label: string, value: number) => `${label}: ${value} av 100`,
    },
    filterLabels: {
      max: "Max",
      from: "Från",
    },
    footer: {
      tagline: "Ett tryggare sätt att välja bil.",
      disclaimer: "Marknadsvärden och kostnader är uppskattningar, inte garantier.",
    },
  },
} as const;
